In [2]:
import numpy as np

In [7]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [8]:
# 1. Matrix manipulation - Swap the second and fourth rows of the data matrix.
data[2,4] = data[4,2]
print(data)

[[46 54 82 22 40]
 [23 78 65 60 59]
 [ 9 27 26 93 48]
 [ 6 58 69 37 74]
 [14  6 48 75 26]]


In [9]:
# 2. Normalization- Normalize all the elements in the data matrix. In this context, normalizing means to scale the values in such a way that they fall within the range of 0 and 1. To achieve this, subtract the minimum value from each element and divide by the range (max-min).
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[[0.45977011 0.55172414 0.87356322 0.18390805 0.3908046 ]
 [0.1954023  0.82758621 0.67816092 0.62068966 0.6091954 ]
 [0.03448276 0.24137931 0.22988506 1.         0.48275862]
 [0.         0.59770115 0.72413793 0.35632184 0.7816092 ]
 [0.09195402 0.         0.48275862 0.79310345 0.22988506]]


In [10]:
# 3. Z-score normalization - Standardize the elements in the data matrix using Z-score normalization. In this method, all the elements will be rescaled to have a mean of 0 and a standard deviation of 1. The formula for Z-score normalization is
# (X - mean) / std , where ( X ) is the element in the data matrix.
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

[[ 0.00800641  0.32826272  1.44915979 -0.95276252 -0.23218582]
 [-0.91273048  1.28903164  0.76861514  0.56845495  0.52842291]
 [-1.47317902 -0.75260232 -0.79263436  1.88951221  0.08807048]
 [-1.59327513  0.48839087  0.92874329 -0.35228194  1.12890348]
 [-1.27301882 -1.59327513  0.08807048  1.16893552 -0.79263436]]


In [24]:
# 4. Array splitting - Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.
flatten = np.ravel(data)
arr1 = flatten[:5]
arr2 = flatten[5:10]
arr3 = flatten[10:15]
arr4 = flatten[15:20]
arr5 = flatten[20:25]
print([arr1, arr2, arr3, arr4, arr5])

[array([46, 54, 82, 22, 40]), array([23, 78, 65, 60, 59]), array([ 9, 27, 26, 93, 48]), array([ 6, 58, 69, 37, 74]), array([14,  6, 48, 75, 26])]


In [28]:
# 5. Dot product - Create two vectors of size 5 with any values. Compute the dot product of the two vectors*.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
res = np.dot(arr1, arr2)
print(res)

130


In [45]:
# 6. Matrix multiplication - Create another 3x3 matrix with any values (let’s call it data2). Perform matrix multiplication (dot product of data (first 3x3 part) and data2).
data2 = np.arange(0,9).reshape(3,3)
data_short = np.concatenate((data[0:3,0], data[0:3,1], data[0:3,2]),axis = 0).reshape(3,3)
res = np.dot(data2, data_short)
print(res)

[[ 218  208   79]
 [ 764  706  265]
 [1310 1204  451]]


In [48]:
# 7.Inverse of a matrix - Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.
data3 = np.eye(3)*2
inverse = np.linalg.inv(data3)
print(inverse)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [50]:
# 8. Eigenvalues and eigenvectors - For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors*.
a = np.linalg.eig(data_short)
print(a)

EigResult(eigenvalues=array([125.88632742,  22.25237369,   1.86129889]), eigenvectors=array([[-0.27376285, -0.56217787, -0.02875879],
       [-0.68778719,  0.73145877, -0.31590512],
       [-0.67231144, -0.38590686,  0.94835483]]))


In [65]:
# 9. Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.
data4 = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
rand_ind = np.random.choice(data4.size, 5, replace=False)
data4 = data4.astype(float)
data4.flat[rand_ind] = np.nan
print(data4)

[[11.  4.  8. 42. 72.]
 [nan 67.  9. 21. 37.]
 [32. 73. 45.  1. nan]
 [85. 15. nan nan 74.]
 [nan 54. 66. 23. 39.]]
