In [2]:
import numpy as np

In [7]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

In [8]:
# 1. Matrix manipulation - Swap the second and fourth rows of the data matrix.
data[2,4] = data[4,2]
print(data)

[[46 54 82 22 40]
 [23 78 65 60 59]
 [ 9 27 26 93 48]
 [ 6 58 69 37 74]
 [14  6 48 75 26]]


In [9]:
# 2. Normalization- Normalize all the elements in the data matrix. In this context, normalizing means to scale the values in such a way that they fall within the range of 0 and 1. To achieve this, subtract the minimum value from each element and divide by the range (max-min).
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[[0.45977011 0.55172414 0.87356322 0.18390805 0.3908046 ]
 [0.1954023  0.82758621 0.67816092 0.62068966 0.6091954 ]
 [0.03448276 0.24137931 0.22988506 1.         0.48275862]
 [0.         0.59770115 0.72413793 0.35632184 0.7816092 ]
 [0.09195402 0.         0.48275862 0.79310345 0.22988506]]


In [10]:
# 3. Z-score normalization - Standardize the elements in the data matrix using Z-score normalization. In this method, all the elements will be rescaled to have a mean of 0 and a standard deviation of 1. The formula for Z-score normalization is
# (X - mean) / std , where ( X ) is the element in the data matrix.
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

[[ 0.00800641  0.32826272  1.44915979 -0.95276252 -0.23218582]
 [-0.91273048  1.28903164  0.76861514  0.56845495  0.52842291]
 [-1.47317902 -0.75260232 -0.79263436  1.88951221  0.08807048]
 [-1.59327513  0.48839087  0.92874329 -0.35228194  1.12890348]
 [-1.27301882 -1.59327513  0.08807048  1.16893552 -0.79263436]]
